"""Topic narration module — wiki-style synthesis pages, one per qualifying tag.

A tag qualifies for a topic page if it appears on >= min_days_for_topic distinct
days across session briefs. This filters burst tags (same day, many sessions)
and ensures the synthesis has meaningful temporal breadth.

Each topic page is stored in narrations (scope='topic', key=<tag>) with a
human-readable prose narrative. The prose is generated by Claude in a
first-person-reflective voice and post-processed by the render pipeline.

This is a parallel branch to the daily/weekly/monthly cascade — topics consume
briefs directly and never feed back into the daily cascade.
"""
from __future__ import annotations

import hashlib
import json
import re
import sqlite3
import subprocess
from datetime import datetime, timezone

from claudejournal.config import Config
from claudejournal.db import connect
from claudejournal.narrate import (
    _annotations_hash_contribution,
    format_pinned_corrections,
    load_annotations_for_scope,
)


# Bump when the topic prompt meaningfully changes — participates in the input
# hash so bumping forces regeneration of all topic pages cleanly.
# v2: annotation prompt-pins added (Phase E v2).
TOPIC_PROMPT_VERSION = "v2"


TOPIC_SYSTEM = """You produce a personal, first-person-reflective wiki page — what the user has come to understand about this topic through their own work. Not a glossary entry; not a news article. Write as if the user is synthesizing their own notes.

Rules:
1. Write in first person. This is the user's voice, not a neutral observer.
2. Prefer their language and framing from the briefs. Reference specific projects and moments where useful.
3. Do NOT retell the journal chronologically — this is a living synthesis, time-agnostic. Distill themes, patterns, insights, recurring challenges.
4. Length: 250–500 words. Dense and useful; no padding.
5. Output plain prose paragraphs only. No headers, no bullet lists, no markdown formatting. Just flowing text that reads well aloud.
6. Do not start with "I" — vary the opening sentence."""


def _safe_slug(tag: str) -> str:
    """Convert a tag name to a filesystem-safe slug.

    Replaces characters that are problematic on Windows/POSIX filesystems
    (slashes, colons, backslashes, angle brackets, pipes, question marks,
    asterisks, quotes) with hyphens. Collapses consecutive hyphens.
    Strips leading/trailing hyphens. Falls back to a hash if the result
    is empty.
    """
    s = tag.lower()
    # Replace any char that's unsafe on common filesystems
    s = re.sub(r'[\\/:*?"<>|]', '-', s)
    # Replace spaces with hyphens
    s = s.replace(' ', '-')
    # Collapse consecutive hyphens
    s = re.sub(r'-{2,}', '-', s)
    s = s.strip('-')
    if not s:
        # Fallback: short hash of the original tag
        s = 'tag-' + hashlib.sha256(tag.encode()).hexdigest()[:8]
    return s


def build_slug_map(tags: list[str]) -> dict[str, str]:
    """Build a collision-safe {tag: slug} mapping for a list of tags.

    If two tags produce the same slug (e.g. "ml/ops" and "ml-ops"), the
    second gets a numeric suffix appended.
    """
    mapping: dict[str, str] = {}
    used: dict[str, int] = {}  # slug -> count of times used
    for tag in sorted(tags):  # sort so collisions resolve deterministically
        slug = _safe_slug(tag)
        if slug in used:
            used[slug] += 1
            slug = f"{slug}-{used[slug]}"
        else:
            used[slug] = 0
        mapping[tag] = slug
    return mapping


def tags_with_enough_coverage(conn: sqlite3.Connection, min_days: int = 3) -> list[str]:
    """Return tags that appear on at least min_days distinct calendar days.

    Uses session_briefs.brief_json (JSON array in 'tags' field). Day-distinctness,
    not brief-count, so burst sessions on the same day count once.
    """
    rows = conn.execute(
        "SELECT date, brief_json FROM session_briefs WHERE date IS NOT NULL AND date != ''"
    ).fetchall()

    # Build per-tag set of distinct days
    tag_days: dict[str, set[str]] = {}
    for r in rows:
        try:
            b = json.loads(r["brief_json"])
        except (json.JSONDecodeError, TypeError):
            continue
        raw = b.get("tags") or []
        if not isinstance(raw, list):
            continue
        date = r["date"]
        for t in raw:
            if not isinstance(t, str):
                continue
            s = t.strip().lower()
            if not s or len(s) > 64:
                continue
            tag_days.setdefault(s, set()).add(date)

    return sorted(t for t, days in tag_days.items() if len(days) >= min_days)


def _day_count_for_tag(conn: sqlite3.Connection, tag: str) -> int:
    """Count distinct days a tag appears on."""
    rows = conn.execute(
        "SELECT date, brief_json FROM session_briefs WHERE date IS NOT NULL AND date != ''"
    ).fetchall()
    days: set[str] = set()
    for r in rows:
        try:
            b = json.loads(r["brief_json"])
        except (json.JSONDecodeError, TypeError):
            continue
        raw = b.get("tags") or []
        if tag in [t.strip().lower() for t in raw if isinstance(t, str)]:
            days.add(r["date"])
    return len(days)


def _load_briefs_for_tag(conn: sqlite3.Connection, tag: str) -> list[dict]:
    """Load all session briefs that include this tag, sorted by date ascending."""
    rows = conn.execute(
        """SELECT b.session_id, b.date, b.brief_json, p.display_name AS project_name
           FROM session_briefs b
           JOIN projects p ON p.id = b.project_id
           WHERE b.date IS NOT NULL
           ORDER BY b.date ASC, b.session_id ASC"""
    ).fetchall()
    results = []
    for r in rows:
        try:
            b = json.loads(r["brief_json"])
        except (json.JSONDecodeError, TypeError):
            continue
        raw = b.get("tags") or []
        if tag not in [t.strip().lower() for t in raw if isinstance(t, str)]:
            continue
        b["_session_id"] = r["session_id"]
        b["_date"] = r["date"]
        b["_project_name"] = r["project_name"]
        results.append(b)
    return results


def _topic_input_hash(tag: str, briefs: list[dict],
                      annotations: list[dict] | None = None) -> str:
    """Deterministic hash over prompt version + tag + brief identifiers + annotations.

    When briefs change (new sessions, updated briefs) the hash changes and
    the topic page regenerates on the next cycle. When annotations change
    (user edits a correction for this topic), the hash also changes, triggering
    re-narration with the updated PINNED CORRECTIONS block.
    """
    h = hashlib.sha256()
    h.update(TOPIC_PROMPT_VERSION.encode())
    h.update(b"\x00")
    h.update(tag.encode("utf-8", errors="replace"))
    h.update(b"\x00")
    # Sort by session_id for determinism across runs
    for b in sorted(briefs, key=lambda x: x.get("_session_id", "")):
        sid = (b.get("_session_id") or "").encode("utf-8", errors="replace")
        # Include the brief's own hash if available, otherwise the goal
        goal = (b.get("goal") or "").encode("utf-8", errors="replace")
        h.update(sid); h.update(b"\x01"); h.update(goal); h.update(b"\x02")
    if annotations:
        h.update(b"\x03annotations\x03")
        h.update(_annotations_hash_contribution(annotations))
    return h.hexdigest()[:16]


def _already_current(conn: sqlite3.Connection, tag: str, input_hash: str) -> bool:
    """True if narrations already has a current topic page for this tag."""
    row = conn.execute(
        "SELECT input_hash, prompt_version FROM narrations WHERE scope='topic' AND key=?",
        (tag,),
    ).fetchone()
    if not row:
        return False
    return row["input_hash"] == input_hash and row["prompt_version"] == TOPIC_PROMPT_VERSION


def _build_topic_message(tag: str, briefs: list[dict],
                         annotations: list[dict] | None = None,
                         max_chars: int = 14000) -> str:
    """Build the user message for the topic synthesis prompt.

    annotations: list of annotation rows for this topic (scope='topic', key=tag).
    If non-empty, a PINNED CORRECTIONS block is inserted after the source
    material and before the final instruction line.
    """
    lines = [f"TOPIC TAG: {tag}", ""]

    # Group briefs by date for context
    by_date: dict[str, list[dict]] = {}
    for b in briefs:
        d = b.get("_date", "unknown")
        by_date.setdefault(d, []).append(b)

    lines.append(f"This tag appears across {len(by_date)} distinct days. Below are the relevant session briefs (oldest first):")
    lines.append("")

    body_parts = []
    for date in sorted(by_date.keys()):
        date_briefs = by_date[date]
        for b in date_briefs:
            proj = b.get("_project_name", "unknown")
            parts = [f"[{date}] Project: {proj}"]
            if b.get("goal"):
                parts.append(f"  Goal: {b['goal']}")
            if b.get("did"):
                parts.append("  Did: " + " | ".join(str(x) for x in b["did"][:5]))
            if b.get("learned"):
                parts.append("  Learned: " + " | ".join(str(x) for x in b["learned"][:3]))
            if b.get("friction"):
                parts.append("  Friction: " + " | ".join(str(x) for x in b["friction"][:3]))
            body_parts.append("\n".join(parts))

    body = "\n\n".join(body_parts)
    if len(body) > max_chars:
        body = body[:max_chars] + "\n...[oldest briefs retained; truncated for length]"

    lines.append(body)
    lines.append("")

    # PINNED CORRECTIONS — user annotations for this topic (Phase E v2).
    # Placed after source material, before the final instruction.
    if annotations:
        lines.append(format_pinned_corrections(annotations))

    lines.append(
        "Write a first-person synthesis of what the user has learned and experienced with this topic. "
        "Plain paragraphs only — no headers, no bullets, no markdown. 250–500 words."
    )
    return "\n".join(lines)


def _call_claude_prose(user_msg: str, system: str, model: str,
                       binary: str = "claude") -> str:
    """Call the Claude CLI for free-prose output (not structured JSON).

    Returns the prose string. Raises RuntimeError on CLI failure.
    """
    from claudejournal.narrator.claude_code import _no_session_leak

    # Map shorthand model aliases to full model IDs
    model_map = {
        "haiku":  "claude-haiku-4-5",
        "sonnet": "claude-sonnet-4-5",
        "opus":   "claude-opus-4-5",
    }
    full_model = model_map.get(model, model)

    cmd = [
        binary, "-p",
        "--model", full_model,
        "--tools", "",
        "--no-session-persistence",
        "--output-format", "json",
        "--system-prompt", system,
    ]
    with _no_session_leak():
        proc = subprocess.run(
            cmd, input=user_msg, capture_output=True, text=True,
            encoding="utf-8", errors="replace", timeout=300,
        )
    if proc.returncode != 0:
        raise RuntimeError(
            f"claude CLI exit {proc.returncode}: {proc.stderr.strip()[:500]}"
        )
    envelope = json.loads(proc.stdout)
    if envelope.get("is_error"):
        raise RuntimeError(f"CLI error: {envelope.get('result', '')[:500]}")
    # Free-prose responses come through the `result` key
    prose = (envelope.get("result") or "").strip()
    if not prose:
        raise RuntimeError(
            f"empty result from CLI; envelope keys: {list(envelope.keys())}"
        )
    return prose


def _persist_topic(conn: sqlite3.Connection, tag: str, prose: str,
                   input_hash: str, model: str) -> None:
    """Upsert a topic narration row."""
    conn.execute(
        """
        INSERT INTO narrations (scope, key, date, project_id, prose,
            prompt_version, input_hash, generated_at, model)
        VALUES ('topic', ?, '', NULL, ?, ?, ?, ?, ?)
        ON CONFLICT(scope, key) DO UPDATE SET
            date = excluded.date,
            project_id = excluded.project_id,
            prose = excluded.prose,
            prompt_version = excluded.prompt_version,
            input_hash = excluded.input_hash,
            generated_at = excluded.generated_at,
            model = excluded.model
        """,
        (
            tag, prose,
            TOPIC_PROMPT_VERSION, input_hash,
            datetime.now(timezone.utc).isoformat(), model,
        ),
    )


def summarize_topic(conn: sqlite3.Connection, tag: str, *,
                    model: str = "haiku", force: bool = False,
                    verbose: bool = True) -> dict:
    """Generate (or regenerate) the synthesis narration for a single topic tag.

    Returns a stats dict with generated/skipped counts.
    """
    briefs = _load_briefs_for_tag(conn, tag)
    if not briefs:
        if verbose:
            print(f"  skip {tag!r}  (no briefs with this tag)")
        return {"generated": 0, "skipped": 1, "reason": "no briefs"}

    # Phase E v2: load topic-scoped annotations so they participate in the hash
    # and are injected into the prompt as PINNED CORRECTIONS.
    annotations = load_annotations_for_scope(conn, "topic", tag)

    ih = _topic_input_hash(tag, briefs, annotations)

    if not force and _already_current(conn, tag, ih):
        if verbose:
            print(f"  skip {tag!r}  (cache hit)")
        return {"generated": 0, "skipped": 1, "reason": "cache"}

    user_msg = _build_topic_message(tag, briefs, annotations)
    prose = _call_claude_prose(user_msg, TOPIC_SYSTEM, model=model)

    _persist_topic(conn, tag, prose, ih, model)
    conn.commit()
    if verbose:
        print(f"  topic {tag!r}  ({len(prose)} chars, model={model})")
    return {"generated": 1, "skipped": 0}


def list_topics(conn: sqlite3.Connection, min_days: int = 3) -> list[dict]:
    """Return all qualifying tags with their page status.

    Status is one of: 'current', 'stale', 'missing'.
    """
    qualifying = tags_with_enough_coverage(conn, min_days)
    results = []
    for tag in qualifying:
        briefs = _load_briefs_for_tag(conn, tag)
        annotations = load_annotations_for_scope(conn, "topic", tag)
        ih = _topic_input_hash(tag, briefs, annotations)
        row = conn.execute(
            "SELECT input_hash, prompt_version, generated_at FROM narrations "
            "WHERE scope='topic' AND key=?",
            (tag,),
        ).fetchone()
        day_count = _day_count_for_tag(conn, tag)
        if not row:
            status = "missing"
        elif row["input_hash"] == ih and row["prompt_version"] == TOPIC_PROMPT_VERSION:
            status = "current"
        else:
            status = "stale"
        results.append({
            "tag": tag,
            "status": status,
            "days": day_count,
            "generated_at": row["generated_at"] if row else None,
        })
    return results


def list_pending(conn: sqlite3.Connection, min_days: int = 3) -> list[str]:
    """Return tags that qualify but have no current topic page."""
    return [t["tag"] for t in list_topics(conn, min_days) if t["status"] != "current"]


def run(cfg: Config, *, all_: bool = True, force: bool = False,
        model: str | None = None, verbose: bool = True,
        progress=None) -> dict:
    """Run the full topic synthesis sweep.

    Loops over all qualifying tags, skipping those with a current hash match
    (unless force=True). Returns aggregate stats.
    """
    def _tick(done: int, total: int, label: str = "") -> None:
        if progress:
            try: progress("topic_summary", done, total, label)
            except Exception: pass

    m = model or cfg.topic_model
    conn = connect(cfg.db_path)
    try:
        tags = tags_with_enough_coverage(conn, cfg.min_days_for_topic)
        total = len(tags)
        stats = {"generated": 0, "skipped": 0, "errors": 0, "total": total}
        _tick(0, max(total, 1), "starting")
        for idx, tag in enumerate(tags, 1):
            _tick(idx, max(total, 1), tag)
            try:
                s = summarize_topic(conn, tag, model=m, force=force, verbose=verbose)
                stats["generated"] += s.get("generated", 0)
                stats["skipped"] += s.get("skipped", 0)
            except Exception as exc:
                stats["errors"] += 1
                if verbose:
                    import sys
                    print(f"  ! topic {tag!r}: {exc}", file=sys.stderr)
        _tick(total, max(total, 1), "done")
    finally:
        conn.close()
    return stats
